name: calculator
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  outline_material_icons: ^0.1.1
  provider: ^4.3.1
  expressions: ^0.1.5
  auto_size_text_field: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Product_Sans
      fonts:
        - asset: fonts/Product_Sans_Regular.ttf
        - asset: fonts/Product_Sans_Bold_Italic.ttf
        - asset: fonts/Product_Sans_Italic.ttf
        - asset: fonts/Product_Sans_Bold.ttf



  uses-material-design: true
